# Generated by Django 3.0.5 on 2020-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='notes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
