# Generated by Django 3.0.5 on 2020-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='cart',
            new_name='cart_one',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='carts.cart_item'),
        ),
    ]
