# Generated by Django 3.0.5 on 2020-04-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_item_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
