# Generated by Django 3.0.5 on 2020-04-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='cart_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carts.cart'),
        ),
    ]
