# Generated by Django 3.0.5 on 2020-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
