# Generated by Django 2.0.3 on 2020-04-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dinner_platter',
            new_name='dinner_platters',
        ),
        migrations.RenameModel(
            old_name='pasta',
            new_name='pastas',
        ),
    ]
