# Generated by Django 3.0.5 on 2020-04-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200419_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salads',
            old_name='pasta_name',
            new_name='salad_name',
        ),
    ]
